#!/usr/bin/env bash
# This script is doing 4, 5, 6, 7 and 8
echo "$$" >/var/run/myscript.pid
trap "echo 'I hate the kill command'; rm /var/run/holbertonscript.pid; exit" SIGTERM
trap "rm /var/run/holbertonscript.pid; exit" SIGQUIT
trap "echo 'Y U no love me?!'" SIGINT
while [ true ]; do
	echo "To infinity and beyond"
	sleep 2
done
