#!/usr/bin/env bash
# This script is displaying /etc/passwd content with phrases
while IFS=":" read -r USERNAME PASSWORD ID GROUP_ID HOME_DIRECTORY COMMAND ID_INFO; do
	echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $COMMAND and rides $ID_INFO. $ID's place is protected by the passcode $PASSWORD, more info about the user here: $HOME_DIRECTORY"
done </etc/passwd
