#!/usr/bin/env bash
# This script is displaying number from 1 to 20 and "bad luck from China" at the 4 time and "bad luck from Japan" at the 9 time and "bad luck from Italy" at the 17 time
i=1
while [ $i -le 20 ]; do
	echo $i
	case $i in
	4)
		echo "bad luck from China"
		;;
	9)
		echo "bad luck from Japan"
		;;
	17)
		echo "bad luck from Italy"
		;;
	esac
	((i++))
done
